run-name: Build and push container to ghcr.io.
on:
    workflow_dispatch:
    schedule:
        - cron: '0 2,14 * * *'
jobs:
    build-container:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: |
                docker build --pull --no-cache --file devtools.dockerfile --tag ghcr.io/mortyr45/archlinux:devtools .
                echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
                docker push ghcr.io/mortyr45/archlinux:devtools
